Makefile update

diff --git a/cs236/Project3/makefile b/cs236/Project3/makefile
--- a/cs236/Project3/makefile
+++ b/cs236/Project3/makefile
@@ -1,24 +1,32 @@
 
-# makefile for project 3 example tests
+
+# makefile for project 3 pass-off tests
 
 NUM:=3
 
-numbers:=30 33 35 36 37 61 62
+buckets:=20 40 60 80 100
+numbers_20:=21 22 24
+numbers_40:=41 42
+numbers_60:=61 62
+numbers_80:=81 82
+numbers_100:=101 102 104 105
 
-tests:=project$(NUM)-tests
+tests:=project$(NUM)-passoff
 
-.SILENT: all run
+.SILENT: all $(buckets)
 
-all: run
-	
-run:
-	for number in $(numbers) ; \
+all: $(buckets)
+
+$(buckets):
+	echo "Bucket $@"; \
+	for number in ${numbers_$@} ; \
 	do \
 		echo "Running input $$number" ; \
-		./proj$(NUM) $(tests)/in$$number.txt > $(tests)/myout$$number.txt ; \
-		diff $(tests)/out$$number.txt $(tests)/myout$$number.txt || (echo "diff failed on test $$number \n") ; \
-	done
+		./lab$(NUM) $(tests)/$@/input$$number.txt > $(tests)/myout$$number.txt ; \
+		diff $(tests)/$@/answer$$number.txt $(tests)/myout$$number.txt || (echo "diff failed on test $$number \n") ; \
+	done \
 
 compile:
-	g++ -Wall -Werror -std=c++17 -g main.cpp -o proj$(NUM)
+	g++ -Wall -Werror -std=c++17 -g main.cpp -o lab$(NUM)
+
 
